### ISSUE TITLE
Explore REST api provided by Google Cloud/Firebase

### ISSUE THREAD

**Issue by katehausladen** [privacy-tech-lab/gpc-web-crawler#25]
Exploring Google Cloud's REST API (https://cloud.google.com/sql/docs/mysql/admin-api) to possibly use for the cloud crawler

**Comment by katehausladen** [comment]
I recreated the table Jocelyn made and enabled the Cloud SQL Admin API for it. It looks like we would need to use the OAuth 2.0 protocol with a service account to authorize requests.


More details:

OAuth 2.0: (documentation: https://developers.google.com/identity/protocols/oauth2)

- According to https://cloud.google.com/sql/docs/mysql/admin-api#enable_the_api, “Every request your application sends to the Cloud SQL Admin API must include an authorization token,” and you can only use the OAuth 2.0 protocol to authorize requests.

Service Account: (documentation:  https://developers.google.com/identity/protocols/oauth2/service-account)

- Since we have a server to server application (no user interaction), I think we need to use the OAuth 2.0 protocol with a service account.

- In the documentation, they recommend that people use client libraries (offered for Java and Python) to avoid having to create and cryptographically sign JSON Web Tokens yourself. 

- There is a client library for JavaScript (https://developers.google.com/identity/oauth2/web/guides/migration-to-gis#implicit_flow_examples), but it is for applications with user interaction (not a service account). We will likely need to use either the Java or Python client library, unless I could figure out a way to just leave out the user interaction.

**Comment by SebastianZimmeck** [comment]
As discussed, what @katehausladen found out seems a bit complicated. A few thoughts:

First, a [Stackoverflow comment](https://stackoverflow.com/a/37263154) claims that "it is not possible to directly connect Javascript to Cloud SQL." This may be true, but it may also have changed since the comment is from 2016. 

We discussed earlier that Firebase (Firestore Database) is not an option. @Jocelyn0830 mentioned that we are using certain APIs in our Firefox extension that makes using Firebase difficult. But wouldn't these APIs only relate to the crawling and not the storage to the database? If so, we could use a similar implementation that we are using for the [GPC Privacy Choice extension](https://github.com/privacy-tech-lab/gpc-privacy-choice). So, please check the readme and ask @ekuller about this.

Here is a [tutorial on Google Cloud and SQL](https://dev.to/wpreble1/deploy-a-full-stack-app-on-gcp-with-a-cloud-sql-connection-part-2-14il). Maybe, not too helpful.

@sophieeng also gets involved in this once the testing implementation is done.

**Comment by Jocelyn0830** [comment]
> First, a [Stackoverflow comment](https://stackoverflow.com/a/37263154) claims that "it is not possible to directly connect Javascript to Cloud SQL." This may be true, but it may also have changed since the comment is from 2016.

I think it is now possible to connect Google Cloud MySQL to as I found many successful cases online. For example, here is a [tutorial](https://billmartin.io/blog/how-to-build-and-deploy-a-nodejs-api-on-google-cloud) written this year that may be helpful to us. 

> We discussed earlier that Firebase (Firestore Database) is not an option. @Jocelyn0830 mentioned that we are using certain APIs in our Firefox extension that makes using Firebase difficult. But wouldn't these APIs only relate to the crawling and not the storage to the database? If so, we could use a similar implementation that we are using for the [GPC Privacy Choice extension](https://github.com/privacy-tech-lab/gpc-privacy-choice).

I believe the problem of Firebase is that Firebase does not support any Firefox addon. Firebase is created for Google Chrome. Details could be found in this [stackoverflow post](https://stackoverflow.com/questions/48518887/firebase-auth-with-firefox-web-extension-add-on#:~:text=You%20can%20also%20submit%20a,ons%20and%20Safari%20extensions%20here.). It is posted in 2021 so it is relatively updated. 

My personal opinion is that we should stick to Google Cloud  MySQL.

**Comment by SebastianZimmeck** [comment]
> Yes, if you submit your work by this Friday, 8 am, we won't deduct any points for lateness.

OK, sounds good, @Jocelyn0830!

**Comment by Jocelyn0830** [comment]
We choose to develop our own rest api. This may be open later if needed.
