### ISSUE TITLE
Analyze and improve performance of cloud and local crawler

### ISSUE THREAD

**Issue by Jocelyn0830** [privacy-tech-lab/gpc-web-crawler#33]
We have developed a crawler that will run in cloud. Now we need to work on improving the performance of the cloud crawler.

**Comment by Jocelyn0830** [comment]
I tried to test our cloud crawler using the old [US privacy string list](https://docs.google.com/spreadsheets/d/1nb6-bI8d6-hDTvoj6Y3YT2HME_qVyHyVOQtY9do_Foo/edit#gid=19659345690) provided by BuiltWith. Below are some issues I noticed: 
1. The crawler stopped after crawling only 48 sites. It printed the below error:
```
selenium WebDriverError: upstream request timeout
```
I hypothesize that there may be some default settings of google cloud or docker selenium that only allow our crawler to work for a short period of time. We need to find out how we can adjust those settings.

2. Upon crawling 48 sites, the success rate is 29/48. We need to improve the success rate. Last time we talked about timeout adjustment. Currently, we set a 7-second timeout in our gpc-analysis-extension. In the crawler, I set a 20-second timeout, which I thought should be more than enough. I do not have any better ideas than doing more testing and experiments.

3.  Not an issue but a future development step. Although now the crawler runs in cloud, we need to trigger it locally from our terminal. Later on we should containerize it and maybe deploy it the google cloud.

**Comment by katehausladen** [comment]
The success rate seems to be much higher when using local docker containers to run the selenium driver. I have consistently gotten around an 88% success rate when using a local docker container ( + the deployed rest api ). Like Jocelyn, I’ve only gotten about a 60% success rate when using the deployed selenium docker container. I’m not sure why using a local container leads to a higher success rate. Looking at the logs of the selenium container in google cloud may be a good starting point to determining why it performs so much worse than the local containers.

Jocelyn mentioned that in her testing, the crawler failed after 48 sites. I made a few updates to the crawler (in issue-33 branch) to help with debugging and crawling more sites in a row.

1. Error catching: I updated the crawler script so that each time an error is caught, the selenium driver restarts. Previously, when an error was caught, the selenium driver would stop working (i.e. no more data would be collected, even though the crawler script would continue to iterate through sites). By restarting the driver, the crawler can continue collecting data where it left off after an error. With this update, the crawler continues collecting data after the Webdriver error Jocelyn mentioned above as well as the most common error I’ve been getting lately: ScriptTimeoutError: Unable to execute request for an existing session: java.net.http.HttpTimeoutException: request timed out. This error seems to happen about once per 42 sites or so, and I think it has to do with a problem loading the site, although sometimes data is still logged in the database about the site that caused the error. The selenium driver fails to restart after the error: WebDriverError: Failed to decode response from marionette. I added --shm-size 2g to the local docker run command (https://github.com/SeleniumHQ/docker-selenium/pull/485/files#diff-04c6e90faac2675aa89e2176d2eec7d8R43) and haven’t gotten that error since. Assuming the driver is able to restart after an error, it seems like the crawler will be able to run for as many sites as you want. I’ve run it for 286 sites (and stopped it manually).
2. Timing: During a crawl, the terminal now prints out how long crawling each site took. From this, I can see that there are certain sites that take longer/cause errors more than others. On average (excluding outliers), it takes 16 seconds to crawl one site using a local docker container. The cloud docker container is slightly slower; on average (excluding outliers) it takes 19 seconds to crawl a site. The outliers are sites that cause errors (that take the 5 min inactivity timeout plus however long it had been running) as well as sites that randomly get stuck for more than a minute but don't cause an official error.

**Comment by Jocelyn0830** [comment]
I am also working on doing some more testing this week. One thing that I considered that might be helpful for our work is to check the performance of the updated analysis functionality. After I implemented the automatic analysis functionality, I tested that it worked when browsing the sites manually. However, I didn't have a chance to test it on a large scale. Now the analysis runs only once on each site. We may modify the script so that it can run twice or more on a given site. I am not sure if this will improve the performance of the crawler, but we can try.

Another thing in case the crawler's performance cannot be improved. Last time when I read the unit testing code of Optmeowt, I noticed some functions that might allow us to load the extension in the Puppeteer (which I thought we could not before). If the Selenium really does not work for us, it might worth investigating into Puppeteer again.

**Comment by SebastianZimmeck** [comment]
As discussed, we decided to stay with Selenium. Two points to explore for the crawler performance are:

- Are sites failing due to the crawler using headless mode? Are they analyzable using headful mode? (If sites are failing because of site issues (e.g., invalid certificate, 404 pages), that should not be counted as a failure in our rate. Only sites that have no issues themselves should be counted.)
- What is the performance of the crawl on the Mac Minis?

**Comment by Jocelyn0830** [comment]
I modified the local headful crawler script to make it more robust and tested its performance. (This is the crawler without docker and google cloud deployment but it still uses the sql database) Now the local crawler automatically restarts when it crashes and continues collecting data where it left off after an error. 

To test its performance, I ran the crawler on 320 sites and the success rate is 310/320. The local crawler worked well with the rest api and sql database. It encountered several errors but each time it successfully restarted from the checkpoint. There was a 6s timeout for each site, so the crawler is running relatively fast. 

However, I am not sure if it will work well on the 10k scale we want, and I need to test it on the Mac minis. Kate and I think it might be reasonable to run the headless crawler first and then run the local headful crawler on sites that failed.
