### ISSUE TITLE
Perform crawl

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-web-crawler#53]
It seems to me we are essentially ready to go.

Should we base our set of sites on the [Tranco List](https://tranco-list.eu/)? I would say, it depends on whether the list has enough sites that are subject to the CCPA. An alternative would be selecting a set from [Built With](https://builtwith.com/). Especially, here is a [list of sites that have some GPC-related code implemented](https://trends.builtwith.com/widgets/Global-Privacy-Control). @katehausladen and @OliverWang13 will look into that.

**Comment by SebastianZimmeck** [comment]
If we opt to use the Tranco List, we can use the daily list (as opposed to the full list).

**Comment by SebastianZimmeck** [comment]
Here is a copy of the Google Sheet with the previous analysis results: [Web_Crawl_Domains}(https://docs.google.com/spreadsheets/d/1ia73RfkYW10FAbjHi7gxax4GPgmpnHxYZ9fw_uSdK1A/edit?usp=sharing). It still has the old results in there for illustration purposes. Those will get replaced with our new results. We can also keep track of the analysis results in a different way than Google Sheets. I am flexible.

**Comment by SebastianZimmeck** [comment]
@OliverWang13 will take the lead on this issue and determine how we select the set of sites for the crawl (about 10K sites in total).

**Comment by OliverWang13** [comment]
Before looking into this at all, my gut instinct was to use the Tranco list to avoid skewing the information to possibly look like way more sites implemented GPC than was representative of all sites. However, it looks like the Tranco list uses sites from all around the world, which would possibly not make much sense for us to analyze. One of the lists that makes up the Tranco, Quantcast, is only of sites in the US, which is closer to what we are looking for but it appears like it is no longer actively updating. I also manually navigated to a few Tranco sites and was unable to reach them.

With these thoughts in mind, I believe the BuiltWith list would be a better choice.

**Comment by OliverWang13** [comment]
The free account can only get 50 entries, while the Basic, Pro, and Team plans can access the full list of 2,768,284 entries.

**Comment by SebastianZimmeck** [comment]
Before we can perform the crawl we first need to test the accuracy of our new methodologies (#54).

**Comment by katehausladen** [comment]
I looked at the distribution of domain extensions for the top 20,000 sites on the Tranco list. 

Here's a visual: 
Note that n ≠ 20,000 because I excluded any domain extensions that had fewer than 200 sites (otherwise it was too cluttered).
<img width="357" alt="Screenshot 2023-09-29 at 2 33 38 PM" src="https://github.com/privacy-tech-lab/gpc-web-crawler/assets/40359590/ff379620-8ade-43e1-b5a3-04ec6a5c4d10">

Just using the .com sites out of the top 20,000 would hit our 10,000 mark. If we want a little wiggle room (since this was the daily list), we could also include .net.

I'll see if I can get an estimate on how many of these .com/.net sites would be subject to the CCPA.

**Comment by SebastianZimmeck** [comment]
Excellent! 

> I'll see if I can get an estimate on how many of these .com/.net sites would be subject to the CCPA.

Yes, that would be a straightforward selection.

**Comment by katehausladen** [comment]
After looking at 75 .com/.net sites from the Tranco list distributed over the range we would be using, I’m not sure this will be a good option. In total, < 50% of .com/.net sites would be subject to the CCPA, with about 30% of sites causing our crawler to restart.

More details:

Nearly 40% of sites (29/75) from the list are useless to us:
- 21/75 of sites had “Server Not Found” errors. These sites would cause the crawler to restart. I think these sites are mostly apis, CDN servers, or DNS servers. Oliver also mentioned this was a problem when he looked at the Tranco list earlier.
- 8/75 sites were not US sites 

The remaining 46/75:
I checked the remaining 46 sites for trackers (of any category) using Firefox’s Enhanced Tracking Protection. 36 sites had a tracker of some kind. Since I allowed any category of tracker, 36/75 would be an upper bound on the number of sites that would be subject to the CCPA.

I checked this by clicking on the shield as shown below.
<img width="320" alt="Screenshot 2023-09-30 at 2 39 12 PM" src="https://github.com/privacy-tech-lab/gpc-web-crawler/assets/40359590/385557d8-fe6c-4f2f-a012-f519f707ff3f">

I'll look into BuiltWith to see if that's a better option.

**Comment by SebastianZimmeck** [comment]
> I'll look into BuiltWith to see if that's a better option.

Sounds good!

**Comment by katehausladen** [comment]
The list of sites is ready. The first 10,000 (exactly) are all under #94,000 on the Tranco list. The distribution is shown below. 
<img width="500" alt="Screenshot 2023-11-07 at 2 18 37 PM" src="https://github.com/privacy-tech-lab/gpc-web-crawler/assets/40359590/39466697-58fe-492c-a4d5-d147e0dc586a">
If we want to end on a round Tranco rank as opposed to exactly 10,000 sites, the first 10,208 are under #100,000 on the Tranco list. 

The sites come from all 50 states. I think the sites are prevalent enough that this is okay. If we decide this is not the case, I can filter by location or collect additional sites.

I'm adding the sites list as well as my methodology for collecting them to the drive.

**Comment by katehausladen** [comment]
Results from the first round of the crawl:

Success rate (after removing error sites): 10690 / 10858 = 98.45%

I looked at some of the 168 sites that failed to be analyzed and they seemed to fall into 2 categories.
1) The site blocked script injection
2) The site kept redirecting between the domain we loaded and some other domain while analysis was running (for instance, https://lausd.net and https://lausd.org). This means that analysis won't fully run for either domain.

If these should be factored into our success rate, then I can look at the logs for all 168 sites.

Methodology:
First, I crawled 8 sets of ~1500 sites. Then, I redid all error sites that had a subdomain with the subdomain removed. (for example,  https://publicphotos.birkenstock.com had an error in the first round, so I redid https://birkenstock.com). There were 658 sites in the redo set.

**Comment by katehausladen** [comment]
We decided we would rely on the raw success rate and then explain where our site failures came from (i.e. sites failed to load, the 2 issues listed above, Insecure certificate, reached error page, etc). I'll write up the specific protocol I followed so that we can use it for our next crawls.
