### ISSUE TITLE
What implementation change, if any, do we need to make given the deprecation of the US Privacy String?

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-web-crawler#60]
The [US Privacy String](https://github.com/InteractiveAdvertisingBureau/USPrivacy/blob/master/CCPA/US%20Privacy%20String.md) (including the [USPAPI](https://github.com/InteractiveAdvertisingBureau/USPrivacy/blob/master/CCPA/USP%20API.md)) will be deprecated on September 30, 2023. The IAB is introducing their [Global Privacy Platform (GPP)](https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform) --- not to be confused with [Global Privacy Control (GPC)](https://globalprivacycontrol.org/); the two are unrelated.

What would we need to change for our crawler to work in the GPP environment? 

@katehausladen and @OliverWang13, can you look into that?

**Comment by SebastianZimmeck** [comment]
Possibly, helpful links:
- [IAB Global Privacy Platform](https://iabtechlab.com/gpp)
- [IAB US State Signal](https://iabtechlab.com/us-state-signals/)
- [IAB Multi-State Privacy Agreement (MSPA)](https://www.iabprivacy.com/#)

**Comment by katehausladen** [comment]
The short answer is that we will need to get the [GPP string](https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/blob/main/Core/Consent%20String%20Specification.md#global-privacy-platform-string) using the `ping` function from the [CMP API](https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/blob/main/Core/CMP%20API%20Specification.md#consent-management-platform-api). In the latest version of the CMP API (1.1), the `ping` function returns this information:
<img width="1133" alt="Screenshot 2023-07-28 at 9 23 11 PM" src="https://github.com/privacy-tech-lab/gpc-web-crawler/assets/40359590/cbc9938c-3fd4-407b-bd87-835561128439">
I think our extension should just get the string from the return object, and we can decode it in the analysis stage.



Some more info on GPP:
GPP merges privacy regulations from different regions into one format. The USPS (as well as other regional strings) will be replaced by the GPP string, which can contain information from multiple regions at once. The format of the GPP string is described in the diagram below, taken from [a webinar about it](https://www.youtube.com/watch?v=rOXXrQdK04E&t=2s):

<img width="500" alt="Screenshot 2023-07-31 at 10 35 27 AM" src="https://github.com/privacy-tech-lab/gpc-web-crawler/assets/40359590/d9f4e41f-e637-475d-a376-a27672f22cd7">

These are the current sections to choose from. 

<img width="500" alt="Screenshot 2023-08-01 at 11 26 02 PM" src="https://github.com/privacy-tech-lab/gpc-web-crawler/assets/40359590/65927865-d29b-4574-ad9c-c2c34945f461">


Section 6 (uspv1) is the USPS we are used to, which will be deprecated. These new US sections contain much more information than the USPS (11-16 fields instead of 4 fields in the USPS). The new fields are listed below:
| Field name | US Sections that have this field |
| ----------- | ------------- |
| Version | 7, 8, 9, 10, 11, 12 |
| SharingNotice | 7, 9, 10, 11, 12 |
| SaleOptOutNotice | 7, 8, 9, 10, 11, 12 |
| SharingOptOutNotice | 7, 8 |
| TargetedAdvertisingOptOutNotice | 7, 9, 10, 11, 12 |
| SensitiveDataProcessingOptOutNotice | 7, 11 |
| SensitiveDataLimitUseNotice | 7, 8 |
| SaleOptOut | 7, 8, 9, 10, 11, 12 |
| SharingOptOut | 7, 8 |
| TargetedAdvertisingOptOut | 7, 9, 10, 11, 12 |
| SensitiveDataProcessing | 7, 8, 9, 10, 11, 12 |
| KnownChildSensitiveDataConsents | 7, 8, 9, 10, 11, 12 |
| PersonalDataConsents | 7, 8 |
| MspaCoveredTransaction | 7, 8, 9, 10, 11, 12 |
| MspaOptOutOptionMode | 7, 8, 9, 10, 11, 12 |
| MspaServiceProviderMode | 7, 8, 9, 10, 11, 12 |

**Comment by SebastianZimmeck** [comment]
Excellent!

**Comment by katehausladen** [comment]
I went through the sites in the paper that were compliant with GPC. From that list, these sites implemented GPP:
[cnn.com](http://cnn.com/)
[al.com](http://al.com/)
[howstuffworks.com](http://howstuffworks.com/)
[mlive.com](http://mlive.com/)
[nj.com](http://nj.com/)
[nydailynews.com](http://nydailynews.com/)
[sciencedaily.com](http://sciencedaily.com/)

Unfortunately, all of these sites use version 1.0 of the CMP API. In this version, the GPP string could be accessed using `getGPPData` rather than `ping`. For example, [cnn.com](http://cnn.com/) returns this for `ping`

<img width="600" alt="Screenshot 2023-08-02 at 10 39 46 AM" src="https://github.com/privacy-tech-lab/gpc-web-crawler/assets/40359590/0f925d0d-ffba-49f0-b5ec-312a1a520879">

And this for `getGPPData`

<img width="600" alt="Screenshot 2023-08-02 at 10 55 59 AM" src="https://github.com/privacy-tech-lab/gpc-web-crawler/assets/40359590/477075f5-65b2-455c-97f2-0218dfe5af3a">

This complicates things on our end a bit, as we can’t get the GPP string from the return object of `ping` until sites reflect version 1.1 of the CMP API. 

First, I’m going to focus on successfully pinging the CMP API from the extension. Using this, I’ll try to identify more sites that implemented GPP (if they exist) and check which version of the CMP API they use. If we want to look at the contents of the GPP strings for sites that use version 1.0, I'll use `getGPPData` for now and then change to using `ping` once sites start to use version 1.1. The switch between these 2 functions should just be a name change.

**Comment by SebastianZimmeck** [comment]
> First, I’m going to focus on successfully pinging the CMP API from the extension.  

> If we want to look at the contents of the GPP strings for sites that use version 1.0, I'll use getGPPData for now and then change to using ping once sites start to use version 1.1. The switch between these 2 functions should just be a name change.

Yes, that is good.

Could we also test every site for both `getGPPData` and `ping`, or is that computationally intensive, too confusing code, ... some other disadvantage?

**Comment by katehausladen** [comment]
Yes, that would also work.

**Comment by SebastianZimmeck** [comment]
> Yes, that would also work.

OK, let's explore that as well then. Especially, if there is a gradual change over a longer period of time it may be worth it to look for both (for a certain time, at least).

**Comment by katehausladen** [comment]
I think I may check the version using `ping` and then look for the GPP string in the appropriate place based on that result (i.e., look inside PingReturn for version 1.1 and check `getGPPData` for version 1.0). `getGPPData` should not exist as a function in version 1.1.

Does that sound ok? I'll go ahead and add columns for the GPP string before and after GPC.

**Comment by SebastianZimmeck** [comment]
> I think I may check the version using `ping` and then ...

But wouldn't `ping` fail, i.e., return nothing at all in case of version 1.0? Or are you saying: 
1. Try `ping`
2. If any value is returned, continue v1.1 logic; if nothing is returned, do `getGPPData`

**Comment by katehausladen** [comment]
No, `ping` is a function in both versions, but the attributes it returns are different based on the version. The version is returned by both versions of `ping`. We use the version to determine where to look for the gppString. Basically, version 1.1 merges version 1.0's `getGPPData` and `ping` into one `ping` function.

Here's a visual that might help:
<img width="650" alt="Screenshot 2023-08-03 at 4 39 45 PM" src="https://github.com/privacy-tech-lab/gpc-web-crawler/assets/40359590/04af3ed3-e526-4292-bfa2-65a088ef3537">

**Comment by SebastianZimmeck** [comment]
Ah, very enlightening, indeed. :)

Yes, the `ping` approach makes sense to me.

**Comment by katehausladen** [comment]
I crawled the last 774 sites of the initial set of ~2000 to test the last commit. It took ~32 s per site. The success rate was 98% when insecure certificates and error pages were excluded. I believe the rest of the failed sites were due to sites not loading (either initially or on the reload). 74 sites in this set had gpp implemented.


Some details on the commit:
The version differences (v 1.0 vs v 1.1) also affected the injected script for gpp set in contentScripts.js. 
<img width="700" alt="Screenshot 2023-08-24 at 11 47 50 PM" src="https://github.com/privacy-tech-lab/gpc-web-crawler/assets/40359590/eca9a865-0d77-4539-a488-4a7066614911">
As shown in the picture, all default gpp functions (including `ping` and `getGPPData`, the ones we are using) used return values in version 1.0 but now have callback functions in version 1.1. All sites with v 1.0 return values as expected, but some execute callback functions and some don’t. 
So, sites fall into 3 categories:

- v 1.1: callback only
- v 1.0: executes callback and returns value
- v 1.0: returns value only

The injection script in the commit accommodates all 3 categories. For all sites that have implemented v 1.1, if you call a default function (I.e. `ping` or `getGPPData`) without a callback, it will use v 1.0 and return a value. However, I wanted v 1.1  to take precedence over v 1.0, so I wrote the injection script such that a callback takes precedence over a return value. Eventually, when v 1.0 stops being used, that injection script can be changed to rely exclusively on callbacks.

Another thing I added was a counter for how many times analysis was started and stopped for each domain. With the counter, we can prevent analysis from starting or stopping twice (or more) in a row for a particular domain. I added this because I was getting multiple entries for some sites. I realized that the sites were somehow loading more than once (or at least the event listener that responds to “load” events is being triggered more than once), which was triggering the extension to start or stop analysis more than once for a particular domain. (The load events happen close enough together that the extension has not updated the variable that stores whether analysis is running). Out of the 774 sites I crawled, these are the sites that loaded multiple times: https://www.furniturerow.com/, https://www.ultrasurfing.com/, https://www.wm.com/, https://www.fee.org/, https://www.ammoland.com/, https://www.upmc.com/. It seems rare enough that it could just be a site issue, and with the counter, analysis runs normally.

**Comment by SebastianZimmeck** [comment]
> The success rate was 98%

> The injection script in the commit accommodates all 3 categories.

> With the counter, we can prevent analysis from starting or stopping twice (or more) in a row for a particular domain.

Excellent!

**Comment by katehausladen** [comment]
The IAB has a [website](https://iabgpp.com/) that encodes and decodes GPP strings. The site uses this [JS/TS package](https://www.npmjs.com/package/@iabgpp/cmpapi) to do the encoding and decoding process. The full package cannot run locally on a computer, as it must be able to access a window object in the browser. Since the package uses an Apache 2.0 license, I decided to just start from the library, remove all code that we won't need to use (we only need to decode), and convert it to python so it can easily integrate with our existing colab notebooks. The python code is now [here in drive](https://drive.google.com/drive/u/1/folders/1RSFVADCyvq4TgRDgsTH7xQ4zY7v18TIb), and there is example usage inside the Processing_Analysis_Data colab.

**Comment by katehausladen** [comment]
The last test I did on GPP (of ~700 sites) found 76 sites with GPP strings. The graph below shows how frequently various combinations of sections were implemented in the GPP strings I found.
<img width="330" alt="Screenshot 2023-09-14 at 2 38 23 PM" src="https://github.com/privacy-tech-lab/gpc-web-crawler/assets/40359590/5dfbeb69-a83a-4177-9923-7cbbe08c4099">
As shown, there are a lot of sites in the 'none' section. This means that either the GPP string was empty or it only had the TCF EU/canada sections. Most sites are implementing some combination of uspv1 (the old US privacy string) and usnatv1 (the union of all the fields of individual states, hence covering all state regulations by implementing this section).

As we discussed in the meeting, the states separate different types of information disclosure (i.e. Sale, Sharing, Targeted Advertising). CA's section uses Sale and Sharing, while all other states use Sale and Targeted Advertising. The national section includes all three. The values N/A, opted out, and not opted out correspond to the value inputs as described  [by IAB](https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/blob/main/Sections/US-National/IAB%20Privacy%E2%80%99s%20National%20Privacy%20Technical%20Specification.md) 
<img width="350" alt="Screenshot 2023-09-14 at 3 08 43 PM" src="https://github.com/privacy-tech-lab/gpc-web-crawler/assets/40359590/b8f25c3d-f4bb-46ca-87c9-689b3bba111b">

I separated the different opt outs into different graphs, shown below.
<img width="500" alt="Screenshot 2023-09-14 at 2 56 16 PM" src="https://github.com/privacy-tech-lab/gpc-web-crawler/assets/40359590/8071e868-8396-49a9-8652-68923de141bf">
<img width="500" alt="Screenshot 2023-09-14 at 2 56 27 PM" src="https://github.com/privacy-tech-lab/gpc-web-crawler/assets/40359590/ed59a2a0-a41a-427d-926b-a8fd5964e907">
<img width="500" alt="Screenshot 2023-09-14 at 2 56 39 PM" src="https://github.com/privacy-tech-lab/gpc-web-crawler/assets/40359590/157f7f76-7297-445c-9842-ce58b0187ff5">

**Comment by SebastianZimmeck** [comment]
> This means that either the GPP string was empty or it only had the TCF EU/canada sections.

I am wondering if we should also consider the TCF EU/Canada sections as well. I could imagine some sites saying, "if we are receiving a GPC (or other privacy preference signal), let's just opt out the user everywhere." 

> Most sites are implementing some combination of uspv1 (the old US privacy string) and usnatv1 (the union of all the fields of individual states, hence covering all state regulations by implementing this section).

What is the `usvav1` string that 2/76 sites implement?

> As we discussed in the meeting, the states separate different types of information disclosure (i.e. Sale, Sharing, Targeted Advertising). 

So, there is no "profiling" despite being [defined in some some laws](https://github.com/privacy-tech-lab/gpc-web-crawler/issues/59#issuecomment-1721773798)?

> I separated the different opt outs into different graphs, shown below.

Nice analysis!

**Comment by katehausladen** [comment]
> I am wondering if we should also consider the TCF EU/Canada sections as well. I could imagine some sites saying, "if we are receiving a GPC (or other privacy preference signal), let's just opt out the user everywhere."

I can work on that

> What is the usvav1 string that 2/76 sites implement?

CA, CO, CT, UT, and VA each have their own section that has fields specific to that state's laws. [usvav1](https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/blob/main/Sections/US-States/VA/GPP%20Extension%3A%20IAB%20Privacy%E2%80%99s%20Virginia%20Privacy%20Technical%20Specification.md) is the section for Virginia. Most sites just chose to implement usnatv1 because then they cover all state laws, as usnatv1 is the union of the fields of all the state sections.

> So, there is no "profiling" despite being https://github.com/privacy-tech-lab/gpc-web-crawler/issues/59#issuecomment-1721773798?

No, there is not any field for profiling. [Here](https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/blob/main/Sections/US-National/IAB%20Privacy%E2%80%99s%20National%20Privacy%20Technical%20Specification.md) is a complete list of fields.

**Comment by katehausladen** [comment]
TCF EU/CA are now included in the decoding process. The updated code is in the drive.
Here is the revised version of the pie chart. It looks like old `uspv1` only has split in half, with half of those sites implementing tcf as well. 
<img width="453" alt="Screenshot 2023-09-20 at 4 00 10 PM" src="https://github.com/privacy-tech-lab/gpc-web-crawler/assets/40359590/8be67ad6-e63e-4755-b781-7031b83509b7">

**Comment by SebastianZimmeck** [comment]
Thanks, @katehausladen! 

And, to clarify, we have the logic for capturing the TCF string in the crawler, right?

**Comment by katehausladen** [comment]
Currently, the crawler gets TCF strings via the GPP string (if those sections are included in the GPP string).

**Comment by SebastianZimmeck** [comment]
Ah, yes, right, that is good!

**Comment by SebastianZimmeck** [comment]
> No, there is not any field for profiling. 

There may be no profiling because maybe the opt out right does not cover profiling, which may be defined in the laws for other reasons, or, at least, does not cover the opt out right via privacy preferences signals. We would need to check the laws. (#59) 

It may also simply the case that as GPP is under development the IAB has not yet added profiling.

**Comment by OliverWang13** [comment]
This has been merged and completed.
